# Generated by Django 4.2 on 2023-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KunUz', '0003_alter_newstype_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='regionalnews',
            name='descriptation',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='regionalnews',
            name='newsTypes',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='regionalnews',
            name='summary',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
