# Generated by Django 4.2 on 2023-05-21 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KunUz', '0006_alter_regionalnews_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regionalnews',
            old_name='text',
            new_name='articels',
        ),
        migrations.RenameField(
            model_name='regionalnews',
            old_name='summary',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='regionalnews',
            name='descriptation',
        ),
    ]
